### ISSUE TITLE
Подсветка синтаксиса SyntaxHighlighter

### ISSUE THREAD

**Issue by ReinRaus** [ReinRaus/HashCodeUserJS#11]
В хроме

```
Uncaught TypeError: Cannot read property 'length' of null VM7596:513
changeStyles VM7596:513
__syntaxHighlight VM7596:631
__addonLoader VM7596:261
```

**Comment by ivanovsuper** [comment]
ждем новой версии api. с текущей версией все равно работать пока не будет.
там добавление стилей некорректно реализовано, иногда такая ошибка бывает, да.

**Comment by ReinRaus** [comment]
Попробуйте beforeInit в новом формате.

**Comment by ivanovsuper** [comment]
beforeInit отлично работает. только вызывается даже если плагин отключен.

**Comment by ReinRaus** [comment]
Исправил загрузку- теперь только включенные запускают события.
