### ISSUE TITLE
Хороший редактор кода

### ISSUE THREAD

**Issue by ReinRaus** [ReinRaus/HashCodeUserJS#19]
Кто-нибудь знает хороший редактор? От CodeMirror у меня уже злость берет.

**Comment by ivanovsuper** [comment]
http://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors

http://ace.c9.io/ выглядит неплохо, как в реальности будет не знаю...

**Comment by ReinRaus** [comment]
Сделал использование ACE, стало гораздо приятнее, только в консоль ошибка приходит, но это не существенно.

**Comment by ReinRaus** [comment]
После длительного использования и тестов АСЕ всем устраивает.
