### ISSUE TITLE
Сохранение настроек

### ISSUE THREAD

**Issue by ivanovsuper** [ReinRaus/HashCodeUserJS#21]
Думаю, что сохранять настройки по всем сайтам не всегда нужно и не всегда настройки по всем сайтам могут совпадать. Можно сделать либо галку "сохранять по всем сайтам", либо галочками указывать по каким сайтам применять настройки.

По дефолту сохранять только для текущего сайта.

Я, например, кроме ХК и меты не читаю ничего, мне настройки математики и сделай сам не нужны, а также подсвечивать синтаксис и высоту кода на русском языке, например, форматировать смысла нет...

**Comment by ReinRaus** [comment]
В ближайшее время сделаю сборщик всего этого как расширения, а не UserJs. Проблема отпадет сама так как можно будет использовать одно хранилище для всех доменов. В UserJs сохранение наверно останется в том же виде.
