### ISSUE TITLE
SyntaxHighlighter внутри цитаты

### ISSUE THREAD

**Issue by ReinRaus** [ReinRaus/HashCodeUserJS#22]
http://hashcode.ru/questions/275868/  

```
>     "1)Airbus Industrie began as a consortium of European aviation firms
> to compete with American companies
> such as Boeing, McDonnell Douglas, and
> Lockheed. While many European aircraft
> were innovative, even the most
> successful had small production runs.
> 
>     2)In 1991, Jean Pierson, then CEO and Managing Director of Airbus
> Industrie, described a number of
```

Строки с 1) и 2) будут подсвечены как код

**Comment by ivanovsuper** [comment]
это ошибка автоопределения языка - расцвечивается как php - по тэгам, не лечится.
а вообще если бы это была цитата, а не код, подсветки бы не было - не так оформлен вопрос. имеется в виду, что 4 пробела внутри цитаты действительно сделали текст кодом, и такой код подсвечивается и по дефолту (prettify) тоже.

**Comment by ReinRaus** [comment]
Да, верно. Это и не нужно лечить. Это неправильная разметка самого вопроса. Извините за беспокойство.
