### ISSUE TITLE
SyntaxHighlighter и подсвеченные ники в коде

### ISSUE THREAD

**Issue by ReinRaus** [ReinRaus/HashCodeUserJS#23]
Пример разметки:  

```
    /[-\w.]+@yandex\.ru/.exec('mail@yandex.ru');
```

@yandex определяется как ник участника и линкуется.  
Пример вопроса с такой разметкой:  
http://hashcode.ru/questions/278699/  
Отображается так:  

```
/[-\w.]+<a rel="noindex,nofollow" href="/users/3378/yandextnu">@yandex</a>\.ru/.exec('mail<a rel="noindex,nofollow" href="/users/3378/yandextnu">@yandex</a>.ru');
```

**Comment by ivanovsuper** [comment]
это делает движок хэшкода. юзер определился как `yandextnu`. сабж тут ни при чем.

**Comment by ReinRaus** [comment]
Да, это делает движок ХэшКода, но как минимум в Хроме это выглядит так:  
![](http://i.imgur.com/Zy6H5Fj.png)

**Comment by ivanovsuper** [comment]
ага, косяк. посмотрю
