### ISSUE TITLE
newAnswersandComments в исследованиях

### ISSUE THREAD

**Issue by zba** [ReinRaus/HashCodeUserJS#5]
Uncaught TypeError: Cannot call method 'replace' of undefined [тут](https://github.com/ReinRaus/HashCodeUserJS/blob/master/addons/newAnswersAndComments.js#L5)

**Comment by ReinRaus** [comment]
Не смог воспроизвести ошибку, есть ли последовательность действий для ее воспроизведения ?

**Comment by ivanovsuper** [comment]
там запятая лишняя в этой строке. может из-за этого все валится остальное?

**Comment by ReinRaus** [comment]
[Эта строка](https://github.com/ReinRaus/HashCodeUserJS/blob/master/addons/newAnswersAndComments.js#L13), после обновления нумерация сменилась.

**Comment by ivanovsuper** [comment]
ну тогда нужен url на котором валится. проверил в исследованиях на мете, хк, русском языке. ошибок нет.
там определяется id вопроса. палец вверх для вопроса/исследования должен быть всегда...

**Comment by zba** [comment]
http://hashcode.ru/research/ просто валится, бразурер chrome, проверил с последним release/ChromeDump
