### ISSUE TITLE
"Настройки отсутствуют" до первого использования аддона

### ISSUE THREAD

**Issue by strol** [ReinRaus/HashCodeUserJS#8]
К примеру, после установки HashCodeUserJS, у любого из аддонов нету title и description до того момента, пока не включить этот аддон и перезагрузить страницу или сохранить настройки для всех сайтов, тогда уже появится title и description, но только у одного аддона, если он был выбран один. Такое нужно проделывать с каждым аддоном и на каждом сайте. То есть, проблема в том, что нельзя почитать название аддона и его описание до его первой  активации, что многих может ввести в ступор, как собственно и меня, потому как я сначала думал, что это от погоды зависит, а потом уже заметил причину.

**Comment by ReinRaus** [comment]
Это происходит из-за слишком сложного механизма обработки настроек :-) Сейчас придумал более простой путь, который также позволит хранить неэкспортируемые настройки, что позволит не засорять глобал.  
Ближайшим обновлением исправлю, но пока работаю над деплоем в виде post-recieve хука (долой деплой.ру) и редактированием «аддонов» прямо в окне браузера, с подсветкой кода, чтобы упростить процесс разработки и внесения правок.

**Comment by strol** [comment]
Будем ждать:)

**Comment by ReinRaus** [comment]
С приходом нового формата проблема ушла.
