### ISSUE TITLE
Странно ведет себя syntaxHighlichter

### ISSUE THREAD

**Issue by ReinRaus** [ReinRaus/HashCodeUserJS#9]
например здесь  
http://hashcode.ru/questions/272053/

**Comment by ivanovsuper** [comment]
см #10

**Comment by ReinRaus** [comment]
Смержил, тестим.

**Comment by ivanovsuper** [comment]
Поблема осталась, она заключается в том, что сначала срабатывает prettify, а потом SyntaxHightLighter пытается расцветить уже расцвеченный код. Тут проблема в порядке выполнения скриптов. У меня в 12-й опере сначала выполняется userjs, а потом скрипты на странице. А в этих скриптах получается, что они выполняются после полной загрузки страницы. В общем ищутся идеи как внедриться в порядок выполнения скриптов или вообще запретить выполнения подсветки с помощью prettify...
